### ISSUE TITLE
Linux (Raspberrypi OS) cannot install Festo-edcon python package above 0.11

### ISSUE THREAD

**Issue by jb-chossat** [Festo-se/festo-edcon#3]
Above 0.11, pip install fails, see attached txt file.
[festo-edcon-install.txt](https://github.com/Festo-se/festo-edcon/files/15146881/festo-edcon-install.txt)

It seems it's coming during the make process ?

The package install fails on a Raspberrypi OS (debian based), but works perfectly on a manjaro laptop (arch linux).

**Comment by elrosch** [comment]
Thanks for reporting.
To me it seems that Raspbian is having issues with PyQt5 (which is a dependency needed for the GUI that has been added recently)
I guess one solution would involve fixing the PyQt5 installation on the raspberry.

Now, for best compatibility I decided to make the GUI an optional install feature (for the latest version 0.14.0).
Obviously the GUI will not work on the raspberry then but the library itself should be fully functional.
The GUI part would then need to be fixed in order to use it on the raspberry.

Please let me know if the recent version 0.14.0 fixes your problems.

**Comment by jb-chossat** [comment]
Hey Elias,
Indeed, 0.14 went through without any problems. Nice !
Thank you very much.
